### ISSUE TITLE
Update Openvpn server to latest version

### ISSUE THREAD

**Issue by jav-12** [d3vilh/openvpn-server#17]
There is a new version for Openvpn: https://github.com/OpenVPN/openvpn/blob/v2.6.9/Changes.rst

How can I update it using the docker-compose? Is there any parameter to set up the version we want?

**Comment by d3vilh** [comment]
Hi @jav-12 
Current openvpn-server container [ version is `0.5.1`](https://github.com/d3vilh/openvpn-server/releases/tag/0.5.1), it is based on stable Alpine linux 3.19 branch, which at the moment has `openvpn (2.6.8-r0)` in repository. 
`2.6.9.1` has [arrived](https://pkgs.alpinelinux.org/package/edge/main/x86/openvpn) to Alpine edge branch couple weeks ago and still under testing phase.
As soon as it will be ported to stable - container will be rebuilt with minor version update.

**Comment by d3vilh** [comment]
We still have `2.6.8-r0` in repo.

**Comment by d3vilh** [comment]
[Alpine 3.20 is out](https://alpinelinux.org/posts/Alpine-3.20.0-released.html) couple of days ago, which does yummy [`openvpn-3.6.10-r0` ](https://pkgs.alpinelinux.org/package/v3.20/main/armhf/openvpn) by default.

I'm rebuilding all the images, soon we'll have Alpine 3.20 with all the new updated packages inside 🚀

**Comment by d3vilh** [comment]
Version [`0.5.4`](https://hub.docker.com/layers/d3vilh/openvpn-server/0.5.4/images/sha256-51a55a6395589b4e17b2e2c07f34390d1fe9b27d89e9f1302550a831b9cccab1?context=explore) available for testing. 
It includes:
* Alpine 3.20 as base image.
* OpenVPN 2.6.10-r0.
* OpenSSL 3.3.0-r2.
* EasyRSA 3.1.7-r0.
* Oath-toolkit 2.6.11-r0.

Build for amd_x64, armv8, armv7, armv6.

**Comment by d3vilh** [comment]
[0.5.4 ](https://github.com/d3vilh/openvpn-server/releases/tag/0.5.4)tested and now officially released.

**Comment by jav-12** [comment]
thanks!
