### ISSUE TITLE
You must define TUN/TAP device (--dev)

### ISSUE THREAD

**Issue by zstergios** [d3vilh/openvpn-server#21]
I am getting closer and closer to make it run.

I see 2 errors
1) IP TABLE DROP
2) You must define TUN/TAP device (--dev)

**Any clue @d3vilh ?**

Configuring networking rules...
net.ipv4.ip_forward = 1
Configuring iptables...
NAT for OpenVPN clients
Blocking ICMP for external clients
Blocking internal home subnet to access from external openvpn clients (Internet still available)
Applying firewall rules
'ptables v1.8.10 (nf_tables): Invalid target name `DROP
Try `iptables -h' or 'iptables --help' for more information.
Additional firewall rules applied.
IPT MASQ Chains:
MASQUERADE  all  --  10.0.70.0/24         anywhere
MASQUERADE  all  --  10.0.71.0/24         anywhere
IPT FWD Chains:
       0        0 DROP       1    --  *      *       10.0.71.0/24         0.0.0.0/0            icmptype 8
       0        0 DROP       1    --  *      *       10.0.71.0/24         0.0.0.0/0            icmptype 0
       0        0 DROP       0    --  *      *       10.0.71.0/24         192.168.88.0/24
       0        0 DROP       0    --  *      *       10.0.70.88           10.0.70.77
Start openvpn process...
Options error: You must define TUN/TAP device (--dev)
Use --help for more information.

**Comment by d3vilh** [comment]
```log
Start openvpn process...
Options error: You must define TUN/TAP device (--dev)
```
It does not like your `server.conf` this time .


Try with the default one, you could later change it in UI:

```config
management 0.0.0.0 2080

port 1194
proto udp
#proto tcp

dev tun

ca pki/ca.crt
cert pki/issued/server.crt
key pki/private/server.key

# cipher AES-256-CBC  # Deprecated since v.0.3. we are using GCM now.
cipher AES-256-GCM
auth SHA512
dh pki/dh.pem

server 10.0.70.0 255.255.255.0
route 10.0.71.0 255.255.255.0
ifconfig-pool-persist pki/ipp.txt
push "route 10.0.60.0 255.255.255.0"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 1.0.0.1"

keepalive 10 120
max-clients 100

persist-key
persist-tun

log         /var/log/openvpn/openvpn.log
verb 4
topology subnet

client-config-dir /etc/openvpn/staticclients
push "redirect-gateway def1 bypass-dhcp"

#ncp-ciphers AES-256-GCM:AES-192-GCM:AES-128-GCM   # Deprecated since v.0.3. we have to use data-ciphers below instead
data-ciphers AES-256-GCM:AES-192-GCM:AES-128-GCM

user nobody
group nogroup

status /var/log/openvpn/openvpn-status.log
explicit-exit-notify 1
crl-verify pki/crl.pem

# 2FA Auth part
# script-security 2
# auth-user-pass-verify /opt/app/oath.sh via-file

# Default openvpn-server configuration file
```

by default it is in ./:
```docker
           - ./server.conf:/etc/openvpn/server.conf
```


This error you may ignore:
```log
'ptables v1.8.10 (nf_tables): Invalid target name DROP Try iptables -h' or 'iptables --help' for more information.
```
As we see below  DROP rules were applied:
```log
0 0 DROP 1 -- * * 10.0.71.0/24 0.0.0.0/0 icmptype 8
0 0 DROP 1 -- * * 10.0.71.0/24 0.0.0.0/0 icmptype 0
0 0 DROP 0 -- * * 10.0.71.0/24 192.168.88.0/24
0 0 DROP 0 -- * * 10.0.70.88 10.0.70.77
```
It is to prevent ping and access between allowed and guest subnets.

**Comment by zstergios** [comment]
Yeah, seems the issue is in the config file,  server.conf is directory (!) ( ~/openvpn-server folder)
https://prnt.sc/ln77lA48KERp

Here there is no file  /etc/openvpn/server.conf

I have manual created it.
Still I am trying to resolve, I will come back later.

**Comment by zstergios** [comment]
I manually created the server.conf file, after I run the command the server.conf **directory** is re-created.

I managed to solve the issue, only if I downloaded the origianl file (maybe it's some kind of encoding, I don't know, I am using notepad ++)

`wget https://raw.githubusercontent.com/d3vilh/openvpn-server/main/server.conf`

**Comment by zstergios** [comment]
I managed to start it, I don't know if I should see something more than the "Start openvpn process..."

https://prnt.sc/3CiCjVlKpCCS

but UI seems not connecting

**Comment by d3vilh** [comment]
Hi @zstergios 
Openvpn-UI takes this information from[ OpenVPN server management console](https://openvpn.net/community-resources/management-interface/), which should be enabled (first line `management 0.0.0.0 2080` in your `server.conf`), up and running.

If you running 2 containers (openvpn server and openvpn ui) - both containers should use the same Docker subnet and management console must be available from openvpn-ui container (by default it takes container name `openvpn` to address  management console.

What you have to do for fix:
* Confirm you have management console enabled on port 2080 in `server.conf`.
* Confirm your openvpn service/container is up and running (`docker ps | grep openvpn`).
* Confirm you have access to management console from host server (with netcat):
```bash
yejik@superserv:~ $ nc -zv $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' openvpn) 2080
Connection to 172.18.0.3 2080 port [tcp/*] succeeded!
yejik@ superserv:~ $
```
* Confirm you have access to management console from the openvpn-ui container:
```bash
yejik@ superserv:~ $ docker exec openvpn-ui sh -c "nc -zv $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' openvpn) 2080"
172.18.0.3 (172.18.0.3:2080) open
yejik@ superserv:~ $
```

if you do have access between containers, than, please share the start logs for both *openvpn* and *openvpn-ui* containers (`docker restart openvpn; docker restart openvpn-ui; docker logs openvpn; docker logs openvpn-ui`)
