### ISSUE TITLE
Not even after user revokes server restart button.

### ISSUE THREAD

**Issue by Leeeuijooo** [d3vilh/openvpn-server#24]
Even if you restart the server after revoke & delete a user, the currently maintained client connection will not be disconnected.
Is there no other way than to restart the container?

The README explains that if you just press the Restart button, the existing connection will be disconnected, but it doesn't work for me.

Any help would be greatly appreciated!

**Comment by d3vilh** [comment]
Hi @Leeeuijooo 
You could "Restart container":
![restsrt-cont](https://github.com/d3vilh/openvpn-server/assets/33333559/965bf5c2-80f8-47bf-8382-7726f4dd72e2)

Or you can kill active session pressing [X] button on main screen.

BTW, please check that revocation went smooth and your CRL has been updated (`$EASY_RSA/pki/crl.pem`) as it should during the revocation procedure. Just confirm that last update time for this file was changed.

**Comment by Leeeuijooo** [comment]
Thank you!!!! I Solved Issue!!!

**Comment by d3vilh** [comment]
closing as solved
