### ISSUE TITLE
iptables v1.8.9 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)

### ISSUE THREAD

**Issue by brwish** [d3vilh/openvpn-server#6]
net.ipv4.ip_forward = 1
Configuring iptables...
NAT for OpenVPN clients
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.9 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
EasyRSA path: /usr/share/easy-rsa OVPN path: /etc/openvpn
PKI already set up.
Following EASYRSA variables were set during CA init:
cat: can't open '/usr/share/easy-rsa/pki/vars': No such file or directory
Configuring networking rules...
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_forward = 1
Configuring iptables...
NAT for OpenVPN clients
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.9 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.

**Comment by d3vilh** [comment]
Hi @brwish, thank you for the reporting this problem.
Could you confirm it is x86 image? Did you build it yourself or pull from the Docker hub?

**Comment by d3vilh** [comment]
Hi @brewish, 
I did a test of the latest docker hub image with [openvpn-aws](https://github.com/d3vilh/openvpn-aws) ( both x86 and arm).
It seems works fine on:
```bash
p@bookworm64:~/openvpn-aws$ cat /etc/debian_version
12.1
p@bookworm64:~/openvpn-aws$ uname -a
Linux bookworm64 6.1.0-12-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.52-1 (2023-09-07) x86_64 GNU/Linux
p@bookworm64:~/openvpn-aws$ docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                                       NAMES
c53a74911aa9   d3vilh/openvpn-server:latest   "/bin/sh -c ./docker…"   4 minutes ago   Up 4 minutes   0.0.0.0:1194->1194/udp, :::1194->1194/udp   openvpn
9c22ad46d4bd   d3vilh/openvpn-ui:latest       "/bin/sh -c /opt/sta…"   4 minutes ago   Up 4 minutes   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   openvpn-ui
p@bookworm64:~/openvpn-aws$ docker logs openvpn
Configuring networking rules...
net.ipv4.ip_forward = 1
Configuring iptables...
NAT for OpenVPN clients
Blocking ICMP for external clients
Blocking internal home subnet to access from external openvpn clients (Internet still available)
No additional firewall rules to apply.
IPT MASQ Chains:
MASQUERADE  all  --  10.0.70.0/24         anywhere
MASQUERADE  all  --  10.0.71.0/24         anywhere
IPT FWD Chains:
       0        0 DROP       1    --  *      *       10.0.71.0/24         0.0.0.0/0            icmptype 8
       0        0 DROP       1    --  *      *       10.0.71.0/24         0.0.0.0/0            icmptype 0
       0        0 DROP       0    --  *      *       10.0.71.0/24         192.168.88.0/24
Start openvpn process...
p@bookworm64:~/openvpn-aws$
```
It first look, your installation is missing Iptables or its modules, confirm it is on the place:
```bash
p@bookworm64:~/openvpn-aws$ dpkg -l | grep iptables
ii  iptables                        1.8.9-2                        amd64        administration tools for packet filtering and NAT
p@bookworm64:~/openvpn-aws$ lsmod | grep iptable
iptable_filter         16384  1
iptable_nat            16384  1
nf_nat                 57344  4 xt_nat,nft_chain_nat,iptable_nat,xt_MASQUERADE
ip_tables              36864  4 iptable_filter,iptable_nat
x_tables               61440  9 xt_conntrack,iptable_filter,nft_compat,xt_tcpudp,xt_addrtype,xt_nat,ip_tables,iptable_nat,xt_MASQUERADE
p@bookworm64:~/openvpn-aws$
```

**Comment by brwish** [comment]
Hi @d3vilh 
It works normally after I use debian system, thank you
