### ISSUE TITLE
IP is not displayed correctly

### ISSUE THREAD

**Issue by pocholo30** [d3vilh/openvpn-server#8]
It works fine but I use as DNS the pihole I have running in docker, both containers are under the same network in docker called netcore. It turns out that the requests in pihole are all shown under the IP of the openvpn-server container (in the docker network). I would like the traffic to be split between each VPN client and not mix all the traffic under the same IP. I have tried to solve this by running both openvpn-server and openvpn-ui but I still manage to configure everything in the UI. Two things happen, the first takes about 10 minutes to start the openvpn service. Once started the requests to the pihole are displayed well but it is the only thing that works correctly because the internet browsing and access to the local network is unusable. I don't know if this can be done in another way to show the IP of each client in the DNS requests without putting the container in network mode host. I don't know what is wrong.

**Comment by d3vilh** [comment]
Hi @pocholo30,
Somehow I missed this issue! Woopsies. 
Interesting issue BTW. What DNS IPs are you using to push on the client side (Is it local PiHole from the docker environment or local home subnet)? 
Do you use static IPs for the VPN clients? 
Finally, as I understand, PiHole is container, so do you have any local to this container DNS records?
