### ISSUE TITLE
./docker-entrypoint.sh: line 82: ./fw-rules.sh: Is a directory

### ISSUE THREAD

**Issue by macollybarbosa** [d3vilh/openvpn-server#9]
Hello, I would like to ask for help because I have a problem with "openvpn-server", I can get it to work, but when I restart the server when I return it shows the log below.

**Container logs**
```
net.ipv4.ip_forward = 1
Configuring iptables...
NAT for OpenVPN clients
Blocking ICMP for external clients
Blocking internal home subnet to access from external openvpn clients (Internet still available)
Applying firewall rules
./docker-entrypoint.sh: line 82: ./fw-rules.sh: Is a directory
```

To make it work again, I need to delete everything and rebuild, this way it works again, but I need to create all the certificates again, but if I restart the docker container it shows the error and no longer starts, could you help me?

**Comment by d3vilh** [comment]
HI @macollybarbosa,
Just arrived from my long vacation and here you are :)
It seems like server is looking for `fw-rules.sh` file in your configuration tree and it has wrong permissions or absent.
Could you tell me the arch of container you are using?

**Comment by keljoundi** [comment]
I am running into the same issue, same lines in the log as posted by @macollybarbosa above. Is there any update on this? @d3vilh, not sure what you mean when asking about the arch of the container but will give you any info that could help. I am running my container within a Ubuntu VM

**Comment by d3vilh** [comment]
Hi @keljoundi thanks for the reporting.
Could you share the image version you are trying to run (`docker inspect --format='{{json .Config.Labels}}' d3vilh/openvpn-server:latest`) and arch+version of OS you are running the image on - `uname -a`.

It should be fixed in 0.4.1 and I just run testing on my x86-64 Debian with latest tag - all seems works good.

**Comment by keljoundi** [comment]
@d3vilh, here ya go
```
ubuntu-vm-docker:~$ docker inspect --format='{{json .Config.Labels}}' d3vilh/openvpn-server:latest
{"maintainer":"Mr.Philipp <d3vilh@github.com>","version":"0.4.1"}
ubuntu-vm-docker:~$ uname -a
Linux ubuntu-vm-docker 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by d3vilh** [comment]
> @d3vilh, here ya go

Did you tried to go with `"version":"0.5.1"`?
Docker treats `./fw-rules.sh` as a directory, so it should exists as file in ./ with RW permissions and all should be fine.

**Comment by zstergios** [comment]
I have same issue. What's is the solution?

```
Configuring networking rules...
net.ipv4.ip_forward = 1
Configuring iptables...
NAT for OpenVPN clients
Blocking ICMP for external clients
Blocking internal home subnet to access from external openvpn clients (Internet still available)
Applying firewall rules
./docker-entrypoint.sh: line 82: ./fw-rules.sh: Is a directory
```

**Comment by zstergios** [comment]
Actually it's directory and not file.

This is empty
https://github.com/d3vilh/openvpn-server/blob/main/fw-rules.sh

**Comment by d3vilh** [comment]
You are right, it is empty, that is why.
I'll add some comment at the beginning as a WA.
